import Head from "next/head";
import Image from "next/image";
// import Header from "../component/header/header";
// import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { Script } from "next/script";
import StatusListCard from "../component/generic/statusListCard";
import mainBg from "../public/assets/img/h1.jpg";
import Slider from "../component/slider"
import { PageSectionA } from "../modules/pageSectionA";
import { PageSectionB } from "../modules/pageSectionB";
import  Welcome  from "../component/welcome";

import Header from "@/components/header";
import AsideNav from "@/components/aside";
import Main from "@/components/main";
export default function Home() {
  const [profile, setprofile] = useState(false);
  const profileStatus = async () => {};
  let page_zindex = ['200',"-199","-198"]
  //setTarget elment at higher z-index





  return (
    <>
      <div  style={{}}>

        <Head>
          <title>blogs</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.o"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <Slider /> */}
        <Header />
        <AsideNav />
        <Main />
        <Main />
        <Main />


        {/* <PageSectionA />
        <Welcome />
        <PageSectionB /> */}





        <br />
        {/* <homesection className={styles.main2}></homesection> */}
      </div>
    </>
  );
}
