import Head from "next/head";


import { useState, useEffect } from "react";




import Header from "@/components/header";
import AsideNav from "@/components/aside/aside";
import Main from "@/components/main/main";
import PortfolioIntro from "@/components/intro/PortfolioIntro";
import Skill from "@/components/intro/Skill";
import DownloadSection from "@/components/Download";
import Projects from "@/components/projects/Projects";
import ProjectCards from "@/components/projects/ProjectsCard";
import { responseApi } from "./api/profile";
import Welcome from "@/components/other/welcome";
import Slider from "@/components/other/slider";
import Layout from "@/components/Layout";
import Darkmode from "@/components/Darkmode";
import SocialMedia from "@/components/socialmedia";
import PortfolioShorts from "@/components/intro/Portfolioshorts";

let intro_info = "Hello, my name is Nilankar. I am a socially conscious individual with experience working with NGOs on social campaigns. In addition to my passion for making a positive impact on society, I also have strong programming skills, including proficiency in programming languages such as C++, Python, and JS. I believe that technology and programming can be powerful tools in driving social change and improving people's lives."
export default function Home() {
  const [profile, setprofile] = useState(false);
  const profileStatus = async () => {};
  let page_zindex = ['200',"-199","-198"]
  //setTarget elment at higher z-index





  return (
    <>
      <div>
        <Head>
          <title>blogs</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.o"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <Slider /> */}

        <Header></Header>
        <AsideNav></AsideNav>
        <Main>
          <PortfolioIntro>
            <Skill />
          </PortfolioIntro>
         <PortfolioShorts info={intro_info} />

          <DownloadSection></DownloadSection>

          <Projects>
           
            <ProjectCards projectslist={responseApi.user[0].profile.projectlist} />
          </Projects>


          <Layout>
           <Welcome />
           <SocialMedia />

          </Layout>


        </Main>

        {/* <PageSectionA />*/}

        {/* <PageSectionB />  */}


        {/* <homesection className={styles.main2}></homesection> */}
      </div>
    </>
  );
}
